package main

import (
	"fmt"
	"log"
	"os"
	"time"

	_ "shbs-server/docs" // generated by `make generate-api` (swag init)

	"shbs-server/cmd/controllers/auth"
	"shbs-server/cmd/controllers/cart"
	"shbs-server/cmd/controllers/image"
	"shbs-server/cmd/controllers/listing"
	"shbs-server/cmd/controllers/message"
	"shbs-server/cmd/controllers/notification"
	"shbs-server/cmd/controllers/order"
	"shbs-server/cmd/controllers/user"
	"shbs-server/cmd/middleware"
	"shbs-server/pkg/config"
	"shbs-server/pkg/services"
	"shbs-server/pkg/util"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
)

//	@title			NDHU Second-Hand Book Store API
//	@version		1.0
//	@description	REST API for the NDHU campus second-hand textbook marketplace.
//	@termsOfService	http://swagger.io/terms/
//	@contact.name	SHBS Dev Team
//	@license.name	MIT
//	@BasePath		/api/v1
//	@securityDefinitions.apikey BearerAuth
//	@in				header
//	@name			Authorization
func main() {
	config.LoadEnvOrFatal()

	db, err := sqlx.Connect("postgres", os.Getenv("DATABASE_URL"))
	if err != nil {
		log.Fatalf("Cannot connect to database: %v", err)
	}
	defer db.Close()

	database := &services.Database{DB: db}

	emailSvc := &services.EmailService{}

	scheduler := services.SetupScheduler(6*time.Hour, func() {
		util.DeleteExpiredTokens(db)
		util.DeleteExpiredVerificationTokens(db)
	})
	defer scheduler.Shutdown()

	app := fiber.New(fiber.Config{
		AppName:   "SHBS API v1",
		BodyLimit: 10 * 1024 * 1024,
	})

	// ── Global middleware ─────────────────────────────────────────────────────
	app.Use(middleware.ErrorHandler())
	app.Use(middleware.CorsHandler())
	app.Use(middleware.PrivateNetworkAccessHandler())
	app.Use(middleware.Logger())
	app.Use(middleware.Compressor())
	app.Use(middleware.RateLimiter())

	// ── Health probes ─────────────────────────────────────────────────────────
	middleware.RegisterHealthChecks(app, database)

	// ── Swagger UI ────────────────────────────────────────────────────────────
	app.Get("/swagger/*", swagger.HandlerDefault)

	// ── Auth routes ───────────────────────────────────────────────────────────
	app.Post("/api/v1/auth/register", func(c *fiber.Ctx) error { return auth.RegisterUser(db, emailSvc, c) })
	app.Post("/api/v1/auth/login", func(c *fiber.Ctx) error { return auth.LoginUser(db, c) })
	app.Post("/api/v1/auth/logout", func(c *fiber.Ctx) error { return auth.LogoutUser(db, c) })
	app.Get("/api/v1/auth/verify", func(c *fiber.Ctx) error { return auth.VerifyEmail(db, c) })
	app.Post("/api/v1/auth/resend-verification", func(c *fiber.Ctx) error { return auth.ResendVerification(db, emailSvc, c) })
	app.Get("/api/v1/auth/sso/login", func(c *fiber.Ctx) error { return auth.SSOLogin(c) })
	app.Get("/api/v1/auth/sso/callback", func(c *fiber.Ctx) error { return auth.SSOCallback(db, c) })

	// ── User routes ───────────────────────────────────────────────────────────
	authMiddleware := middleware.Auth(db)
	app.Get("/api/v1/users/me", authMiddleware, func(c *fiber.Ctx) error { return user.GetMe(db, c) })
	app.Put("/api/v1/users/me", authMiddleware, func(c *fiber.Ctx) error { return user.UpdateMe(db, c) })

	// ── Image routes ──────────────────────────────────────────────────────────
	app.Post("/api/v1/images", authMiddleware, func(c *fiber.Ctx) error { return image.RegisterImage(db, c) })
	app.Get("/api/v1/images/:id", func(c *fiber.Ctx) error { return image.GetImage(db, c) })

	// ── Listing routes ────────────────────────────────────────────────────────
	app.Get("/api/v1/listings", func(c *fiber.Ctx) error { return listing.GetListings(db, c) })
	app.Get("/api/v1/listings/me", authMiddleware, func(c *fiber.Ctx) error { return listing.GetMyListings(db, c) })
	app.Get("/api/v1/listings/:id", func(c *fiber.Ctx) error { return listing.GetListing(db, c) })
	app.Post("/api/v1/listings", authMiddleware, func(c *fiber.Ctx) error { return listing.CreateListing(db, c) })
	app.Patch("/api/v1/listings/:id", authMiddleware, func(c *fiber.Ctx) error { return listing.UpdateListing(db, c) })
	app.Delete("/api/v1/listings/:id", authMiddleware, func(c *fiber.Ctx) error { return listing.DeleteListing(db, c) })

	// ── Cart routes ───────────────────────────────────────────────────────────
	app.Get("/api/v1/cart", authMiddleware, func(c *fiber.Ctx) error { return cart.GetCart(db, c) })
	app.Post("/api/v1/cart", authMiddleware, func(c *fiber.Ctx) error { return cart.AddToCart(db, c) })
	app.Delete("/api/v1/cart/:id", authMiddleware, func(c *fiber.Ctx) error { return cart.RemoveFromCart(db, c) })

	// ── Order routes ──────────────────────────────────────────────────────────
	app.Post("/api/v1/orders", authMiddleware, func(c *fiber.Ctx) error { return order.Checkout(db, c) })
	app.Get("/api/v1/orders", authMiddleware, func(c *fiber.Ctx) error { return order.GetOrders(db, c) })

	// ── Message routes ────────────────────────────────────────────────────────
	app.Get("/api/v1/messages/unread-count", authMiddleware, func(c *fiber.Ctx) error { return message.GetUnreadMessageCount(db, c) })
	app.Get("/api/v1/messages/conversations", authMiddleware, func(c *fiber.Ctx) error { return message.GetConversations(db, c) })
	app.Patch("/api/v1/messages/:id/read", authMiddleware, func(c *fiber.Ctx) error { return message.MarkMessageAsRead(db, c) })
	app.Get("/api/v1/listings/:listingId/messages", authMiddleware, func(c *fiber.Ctx) error { return message.GetMessages(db, c) })
	app.Post("/api/v1/listings/:listingId/messages", authMiddleware, func(c *fiber.Ctx) error { return message.SendMessage(db, c) })

	// ── Notification routes ───────────────────────────────────────────────────
	app.Get("/api/v1/notifications", authMiddleware, func(c *fiber.Ctx) error { return notification.GetNotifications(db, c) })
	app.Get("/api/v1/notifications/unread-count", authMiddleware, func(c *fiber.Ctx) error { return notification.GetUnreadNotificationCount(db, c) })
	app.Patch("/api/v1/notifications/read-all", authMiddleware, func(c *fiber.Ctx) error { return notification.MarkAllNotificationsAsRead(db, c) })
	app.Patch("/api/v1/notifications/:id/read", authMiddleware, func(c *fiber.Ctx) error { return notification.MarkNotificationAsRead(db, c) })

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	log.Printf("SHBS API listening on :%s", port)
	log.Fatal(app.Listen(fmt.Sprintf(":%s", port)))
}
